### PR TITLE
Save achievement progress on exit

### PR DESCRIPTION
**Pull request by WuestFlorian**
Closes Gamify-IT/issues#428

For testing: 
  1. play any course and get some progress at an achievement (just walk around)
  2. leave the course
  3. enter the course again and check, whether the progress was safed or not

Disclaimer: Closing the tab does not result in any saving, so don't do that

### CODE REVIEW

**Comment by delvh** [comment]
>  Disclaimer: Closing the tab does not result in any saving, so don't do that

you may want https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Review by PatrickHoltz — CHANGES_REQUESTED** [review]
I supposed I have to run the dev-e2e docker file. Going back to landing page and back to the course didn't save the progress.

**Review by PatrickHoltz — COMMENTED** [review]
I suppose I have to run the docker dev-e2e file? Use the main-branch in the backend?

**Comment by WuestFlorian** [comment]
> I suppose I have to run the docker dev-e2e file? Use the main-branch in the backend?

No, you can simply use the development server :)

**Review by PatrickHoltz — APPROVED** [review]

**Pull request merged**
