### PR TITLE
add more info to barriers

### PR DESCRIPTION
**Pull request by Gr33ndev**
Closes Gamify-IT/issues#323

For testing, you can use the giliTest course on [dev-server](https://goulburn.informatik.uni-stuttgart.de:9443/).

Not unlockable: 
2023-01-18_19h31_44

Unlock other Dungeon in same world first:
2023-01-18_20h48_492023-01-18_20h49_29

Play more Minigames in same World to unlock:
2023-01-18_19h38_02

Play more Minigames in Dungeon in same World to unlock:
2023-01-18_22h50_382023-01-18_22h54_36

Play more Minigames in other World to unlock:
2023-01-18_22h56_06

Play more Minigames in Dungeon in other World to unlock:
2023-01-18_22h58_32

I don't exactly know why but sometimes unlocking doesn't work (0 minigames to unlock but still not unlocked) so I added an error message:
2023-01-19_00h58_10

### CODE REVIEW

**Comment by delvh** [comment]
I have an idea not to write less code, but to improve the readability: Extract sub methods.

**Comment by Gr33ndev** [comment]
> I have an idea not to write less code, but to improve the readability: Extract sub methods.

Ok right, I'll do that in a minute

**Review by PatrickHoltz — COMMENTED** [review]
Seems to work. It can be questioned, whether the dungeon id as an infoscreen is useful to the player as he only knows where dungeons are placed.
Also in my opinion, the GameManager should not be responsible for generating texts, it should only provide other objects with information about the game. If splitting up this would take a lot of time, I'm fine with leaving it as it is.

**Comment by Gr33ndev** [comment]
Yes, although at each entrance is always which dungeon it is and they should search the dungeons yes.

I had also already thought about moving the text generation in an own manager, will probably still do that.

**Comment by Gr33ndev** [comment]
Is approved by @WuestFlorian, he has GitHub account issues

**Review by PatrickHoltz — APPROVED** [review]

**Pull request merged**
