### PR TITLE
zoom out game

### PR DESCRIPTION
**Pull request by cdingm**
part of Gamify-IT/issues#188
i added functionality for the game zoom. as suggested, you can change the game zoom in runtime.
it has the 3 zoom steps you can see in the survey i made in discord

9 zooms out
0 zooms in

the minimap also zooms out when you zoom out the game, and changes the maximum and minimum minimap zoom levels

then i needed to fix the worlds so we dont see void on the minimap. i also changed the collider of loading world 4 from world 3

i renamed the minimap zoom script, since it no longer only zooms the minimap, but also handles the game zoom

please also test locally with docker

### CODE REVIEW

**Comment by cdingm** [comment]
i maybe need to add the 2 new keys to the keybindings HUD

**Review by WuestFlorian — APPROVED** [review]

**Comment by WuestFlorian** [comment]
We need to enlarge the worlds to prevent people from seeing blank space. But that is not part of that issue.

**Comment by cdingm** [comment]
> We need to enlarge the worlds to prevent people from seeing blank space. But that is not part of that issue.

i believe you can only see blank space where world 5 should be

or did you find other places?

**Review by robojones — APPROVED** [review]
Tried it out. Works fine 👌

**Review by Gr33ndev — APPROVED** [review]

**Comment by delvh** [comment]
How many more reviews do we need before merging?
I'd like to close the issue today.

**Comment by cdingm** [comment]
> How many more reviews do we need before merging? I'd like to close the issue today.

as per https://github.com/Gamify-IT/docs/blob/main/dev-manuals/repositories/repository-guide.md#pull-requests 2 reviews are required and everyone is allowed to merge. I was at work so i couldnt do it till now

**Pull request merged**
