### PR TITLE
fix info popup to don't stack & be removed correctly

### PR DESCRIPTION
**Pull request by Gr33ndev**
Closes Gamify-IT/issues#392

To test try to stack info popups (for example the one from the barrier to world 2)

### CODE REVIEW

**Review by PatrickHoltz — COMMENTED** [review]
The popup does'nt stack anymore. However, there seems to be a flickering on the popup in the beginning the player enters the Barrier.

**Comment by Gr33ndev** [comment]
Oh yes you are totally right. I believe this is because the barrier has 3 BoxColliders. I will try to fix this.

**Comment by Gr33ndev** [comment]
Just tried to remove the "Is Trigger" BoxCollider with the size 2x2 and the flickering disappeared. @WuestFlorian is there a tease that the barrier has this BoxCollider?

**Review by WuestFlorian — APPROVED** [review]

**Comment by Gr33ndev** [comment]
Please merge if approved

**Pull request merged**
