### PR TITLE
Complete teleport functionality

### PR DESCRIPTION
**Pull request by PatrickHoltz**
This completes the teleporters in the overworld frontend. New features:

- there exist teleporters all over world 1 and 2 and their dungeons
- teleporter data is now saved in the frontend so only unlocked teleporters need to be saved in the backend
- fixed several loading issues and other bugs
- teleporters have a new sprite

To test this, you can start the offline mode in the Unity Editor and walk around, find teleporters, unlock them and teleport to other teleporters. However, to test this in combination with the backend, it's optimal to start the docker compose file "docker-compose-dev.yaml".
Instructions for docker can be found here: https://github.com/Gamify-IT/docs/blob/main/dev-manuals/languages/docker/docker-compose.md
For testing you can orient towards the teleporter testplan existing in https://github.com/Gamify-IT/docs/blob/main/dev-manuals/test-plans/overworld/u-overworld-25-teleporter-unlocking
(The docker-compose file will work together with the feature/teleporters branch in the overworld-backend and will be changed before merging this branch into main.)

Closes Gamify-IT/issues#390

### CODE REVIEW

**Comment by delvh** [comment]
Is this PR related to any issue?

**Comment by PatrickHoltz** [comment]
> Is this PR related to any issue?

It's related to https://github.com/Gamify-IT/issues/issues/390 but does not directly close it because the overworld backend is also related to it.

**Review by C0okiedestroyer — COMMENTED** [review]
I tested it in unity and it worked well

**Comment by Gr33ndev** [comment]
sometimes you get stuck in the teleporter & a nullpointer occures..

**Review by WuestFlorian — APPROVED** [review]

**Review by Gr33ndev — APPROVED** [review]

**Pull request merged**
