### PR TITLE
add character selection

### PR DESCRIPTION
**Pull request by cdingm**
part of Gamify-IT/issues#188
image

added a character selection scene, which can be reached through the pause menu. 
selection of 4 characters for demonstration purposes.
only the current player character has the confirm button.
Confirm button actually does nothing because this is not planned for now.

left and right buttons switch character preview

### CODE REVIEW

**Review by WuestFlorian — APPROVED** [review]

**Comment by WuestFlorian** [comment]
I would prefer a character selection in the style of the achievements menu, but that is personal preference.

**Comment by delvh** [comment]
Shouldn't we also save the character on the backend, or can just change your character at any point in time, and you simply start with the default character?

**Review by robojones — APPROVED** [review]
Does what it should do. Good work 👍

**Review by Gr33ndev — APPROVED** [review]

**Comment by cdingm** [comment]
> Shouldn't we also save the character on the backend, or can you just change your character at any point in time, and you simply start with the default character? (I'm fine with either way.)

since we are not implementing a working selection, and just a "to be safe" mockup, i believe this is not needed for now. When you would go to implementing a functionality, you would need to think about that

**Pull request merged**
