### PR TITLE
Feature/integrate hud

### PR DESCRIPTION
**Pull request by cdingm**
Closes Gamify-IT/issues#67

### CODE REVIEW

**Comment by cdingm** [comment]
So this is my first Concept of loading the different scenes needed.
I need some feedback from the overworld team on how they want to load scenes
this also helps @IlijazM issue https://github.com/Gamify-IT/overworld/issues/6 because scne loading is done through script here

**Comment by cdingm** [comment]
Screenshot 2022-06-30 103141
the scenes we want to load with script need to be drag and dropped into the build settings

**Comment by marlau97** [comment]
I reverted my change. The reason is you use the Start() method here so you instantly initialize the right scene and HUD on the game's startup, but it's problematic using this in Gamify-IT/issues#16 because the method gets called when it is not needed, so I still had to make an extra script that only calls for a scene transition when the player enters. 

From my side it's fine initializing the game like this, though I'd appreciate if you renamed the needed scene and script to something that reflects that it will only be used to initialize the game

**Comment by cdingm** [comment]
> I reverted my change. The reason is you use the Start() method here so you instantly initialize the right scene and HUD on the game's startup, but it's problematic using this in [Gamify-IT/issues#16](https://github.com/Gamify-IT/issues/issues/16) because the method gets called when it is not needed, so I still had to make an extra script that only calls for a scene transition when the player enters.
> 
> From my side it's fine initializing the game like this, though I'd appreciate if you renamed the needed scene and script to something that reflects that it will only be used to initialize the game

yeah it really depends if we load into a menu or not, a Class can be created for scene loading also, would be smarter than having it in start

**Comment by Gr33ndev** [comment]
Unfortunately I don't understand what I have to do to get the HUD displayed....

**Comment by cdingm** [comment]
sorry, my last commit had a bug where i forgot to rename something in the script, now you should only need to press start to see area 1 and the hud. if not you need to load the Scene: FirsScene.
This scene can later be edited to whatever we need, but it executes the script which loads the needed scenes: eg Area 1 and HUD
In the script we can later decide what the starting scene has to be

**Review by WuestFlorian — APPROVED** [review]

**Comment by Gr33ndev** [comment]
A Unity reload fixed the problem

**Review by Gr33ndev — APPROVED** [review]

**Review by LeviUniAcc — APPROVED** [review]

**Pull request merged**
