### PR TITLE
add raccoon Tiles set

### PR DESCRIPTION
**Pull request by leonleoff**

### CODE REVIEW

**Comment by leonleoff** [comment]
Not finished, missing npc logic.

**Comment by delvh** [comment]
There is something called `WIP`/ `Draft` status.
I think that would be more fitting here, correct?

**Review by Gr33ndev — APPROVED** [review]

**Comment by delvh** [comment]
Closes Gamify-IT/issues#100.

**Comment by delvh** [comment]
Or doesn't it?

**Pull request merged**
