### PR TITLE
add the 6 additional minigame spots to savanna scene

### PR DESCRIPTION
**Pull request by cdingm**
they got lost during conversion of world 1 because they were added after i already worked on the changing of the theme

### CODE REVIEW

**Comment by cdingm** [comment]
missing
these were added according to the ones added in the Area 1 scene

**Comment by cdingm** [comment]
ich hab grad noch link oben den fehler mit dem busch der einen eingang blockiert gesehen und behoben

**Review by WuestFlorian — APPROVED** [review]

**Comment by Gr33ndev** [comment]
when merged this will propably breake the access of dungeon 1

**Comment by Gr33ndev** [comment]
& FirstScene doesn't load savanna but area 1

**Review by Gr33ndev — APPROVED** [review]

**Pull request merged**
