### PR TITLE
Make keybindings changeable

### PR DESCRIPTION
**Pull request by Gr33ndev**
Closes Gamify-IT/issues#368

**Please merge ASAP to avoid conflicts**

**To test:** 
Change every Keybinding an try:
- Walking
- Sprinting
- Reading a book
- Talking to NPC
- Reading a Sign
- Reading the Map
- Zoom Minimap
- Zoom Game
- Reach pause menu with (newly assigned) escape button
- etc.

### CODE REVIEW

**Review by C0okiedestroyer — COMMENTED** [review]
changing keybindings works, but swapping 2 or more keybindings without assining one to something else first doesnt. for example you cant swap a and w without putting one key to an unused one first even if after the changes every key is only used once.
(I dont know if the following was broken before changes)
you can also interact with objects while in the keychange menu and the game zoom in zoom out changes the minimap and main view

**Comment by marlau97** [comment]
> you can also interact with objects while in the keychange menu and the game zoom in zoom out changes the minimap and main view

Actually this is a bug in every sub menu, I am creating an issue for this

**Comment by Gr33ndev** [comment]
> A few binds can not be assigned, for example mouse wheel up and down

I think these binds aren'T possible with our implementation..

**Review by C0okiedestroyer — COMMENTED** [review]
Seems to work fine now. But if you change the escape key you still need to press the old one first to get out of the keychange menu and then the changes apply.

**Review by PatrickHoltz — COMMENTED** [review]
Every keybind can be changed.
The red indication showing that the same key is bound to multiple controls sometimes doesn't work correctly.
E.g. I change "move right" from D to E. Now its marked red. When I now change "interact" from E to D it also shows up red but should'nt. That has the consequence that the changes are not saved even though they are  legitimate.

**Review by PatrickHoltz — APPROVED** [review]

**Pull request merged**
