### PR TITLE
Set courseId & playerId dynamically

### PR DESCRIPTION
**Pull request by Gr33ndev**
Part of Gamify-IT/issues#251

### CODE REVIEW

**Comment by delvh** [comment]
Erm…
Are you really still splitting by id instead of in the path?
Didn't we want to abandon doing that?

**Comment by Gr33ndev** [comment]
Yes, but at the moment there is still a # everywhere… But as soon as you change it you just have to replace the # with a /...

**Comment by delvh** [comment]
You have to start changing it somewhere?

**Comment by Gr33ndev** [comment]
Yes but I would do it everywhere at once and not willy-nilly just start here....

**Comment by delvh** [comment]
Fine for me.
Do we need an issue for it?

**Comment by Gr33ndev** [comment]
I think so…

**Comment by LeviUniAcc** [comment]
we already have on i think: [#268](https://github.com/Gamify-IT/issues/issues/268)

**Review by marlau97 — APPROVED** [review]

**Review by LeviUniAcc — APPROVED** [review]
lgtm

**Pull request merged**
