### PR TITLE
Fix world 1 and dungeon 1-4 colliders

### PR DESCRIPTION
**Pull request by cdingm**
Closes Gamify-IT/issues#221

This fixes all the colliders of world 1 and the dungeons 1-4
To test this, run around the overworld and run against all the objects/houses etc and try to see if every collider is good, and that the player cant clip through anything.

If you find something that isnt fixed, please screenshot it so i can investigate what the problem is

### CODE REVIEW

**Comment by cdingm** [comment]
image
thanks unity ^^

**Comment by Gr33ndev** [comment]
you can not get closer than this to the fence 2022-08-22_23h10_21

**Comment by Gr33ndev** [comment]
you can not get behind npcs  2022-08-22_23h11_20

**Comment by Gr33ndev** [comment]
tombstones 2022-08-22_23h12_01

**Comment by Gr33ndev** [comment]
flowerpods
2022-08-22_23h12_26

**Comment by Gr33ndev** [comment]
can't go behind stones
2022-08-22_23h12_49


can't go behind fountain
2022-08-22_23h14_11


the other flowerpod
2022-08-22_23h14_45


mini flowerpods
2022-08-22_23h15_09

**Comment by Gr33ndev** [comment]
stones in dungeons
2022-08-22_23h16_18

bones
2022-08-22_23h16_54

statues
2022-08-22_23h17_14

other stones
2022-08-22_23h17_51

ministones
2022-08-22_23h18_22

bridge
2022-08-22_23h18_58
2022-08-22_23h19_05
2022-08-22_23h19_25
2022-08-22_23h19_29

**Review by Gr33ndev — CHANGES_REQUESTED** [review]
Everything else looks very good for me. Thank you for your effort!

**Comment by cdingm** [comment]
Getting behind dungeon objects could be a Problem, because the objects layer doesn't work correctly in the dungeon scene. The player always clips through and I don't know why. I will look into the rest again and see why it happened, because I believe some of that was fixed at some point

**Comment by cdingm** [comment]
World 1 should be now fixed. I may have found the Problem in the dungeons, but i need to redo some of the changes and suggestions, and copy the dungeons again (maybe i should copy them at the very end when i got approvals)

**Review by Gr33ndev — APPROVED** [review]

**Review by WuestFlorian — APPROVED** [review]

**Comment by delvh** [comment]
Before you merge this PR:
**All** dungeons currently use the tileset of world 1, right?
Wouldn't it be good to copy the current tileset of dungeon 1 then to **all** dungeons?

**Comment by cdingm** [comment]
> Before you merge this PR: **All** dungeons currently use the tileset of world 1, right? Wouldn't it be good to copy the current tileset of dungeon 1 then to **all** dungeons?

they all use the cave tileset

**Comment by cdingm** [comment]
image
this is what happens when you copy 15 scenes in unity

**Pull request merged**
