### PR TITLE
add Books to World 1 and Dungeons

### PR DESCRIPTION
**Pull request by cdingm**
Part of Gamify-IT/issues#334

adds 5 configurable Books to World 1 and all Dungeons

To test this, open the overworld and see if there are 5 Books in the world and in the dungeons

books

books_1

### CODE REVIEW

**Comment by delvh** [comment]
Is that change also mirrored to all remaining dungeons?

**Comment by cdingm** [comment]
> Is that change also mirrored to all remaining dungeons?

yes

**Review by WuestFlorian — APPROVED** [review]

**Comment by cdingm** [comment]
This will no longer be merged through this branch. To avoid merge conflicts that happened, changes will be added to https://github.com/Gamify-IT/overworld/pull/128

**Comment by delvh** [comment]
So I can close this PR?

**Comment by cdingm** [comment]
> So I can close this PR?

i will close it soon, i will copy the decription and stuff

**Comment by delvh** [comment]
Can the branch be deleted as well?

**Pull request closed without merging**
