### PR TITLE
polish savana's colliders, rendering order and tile placements

### PR DESCRIPTION
**Pull request by IlijazM**
Closes Gamify-IT/issues#111
Closes Gamify-IT/issues#125
Closes Gamify-IT/issues#156
the polishing is not complete yet but we should have small merges so we don't have a huge merge conflict at the end

### CODE REVIEW

**Comment by Gr33ndev** [comment]
fixing this merge conflict is harder than I thought, because unity completely destroys the sprites in worlds 1 and 3... we should get together and see how we can get this solved.... @IlijazM

**Comment by delvh** [comment]
Could you perhaps try to add the `.gitattributes` of the `main` branch to this branch, to see if it makes merging easier?

**Comment by cdingm** [comment]
i dont think this is mergeable anymore.
current solution in main:
image
this solution:
image
The problem is that the whole construct of the overworld relies on this, (also HUD icons, colliders etc).

**Review by Gr33ndev — APPROVED** [review]

**Review by cdingm — APPROVED** [review]
there are still some minor layer issues but its better than before

**Comment by delvh** [comment]
Will merge in 15 minutes unless anyone objects.

**Comment by delvh** [comment]
Correction: Fix the merge conflict first.

**Comment by delvh** [comment]
Can I add the new UUID that is the conflict?

**Review by delvh — DISMISSED** [review]
Blocking until review.
Feel free to dismiss afterwards.

**Comment by delvh** [comment]
Waiting for merge conflicts to be resolved. You have hopefully learned by now not to leave branches in Overworld for too long.
Oh, ... thinking about it: Isn't @IlijazM now on vacation?
Could someone else do it for him then?

**Comment by cdingm** [comment]
> Waiting for merge conflicts to be resolved. You have hopefully learned by now not to leave branches in Overworld for too long. Oh, ... thinking about it: Isn't @IlijazM now on vacation? Could someone else do it for him then?

i will quickly merge fix this

**Pull request merged**
